title: Comedy Transcripts
description: Audio transcripts from comedy shows
baseurl: "/comedybot" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol, leave empty for GitHub Pages

# Jekyll settings
permalink: pretty

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Data settings
data_dir: assets/audio

# Collections
collections:
  players:
    output: true
    permalink: /player/:title
  themes:
    output: true
    permalink: /themes/:title
  joke_types:
    output: true
    permalink: /joke-types/:title
  bits:
    output: true
    permalink: /bits/:name

defaults:
  - scope:
      path: ""
      type: "players"
    values:
      layout: "player"
  - scope:
      path: ""
      type: "themes"
    values:
      layout: "theme"
  - scope:
      path: ""
      type: "joke_types"
    values:
      layout: "joke_type"
  - scope:
      path: ""
      type: "bits"
    values:
      layout: "bit"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
